name: Deploy SSH VM native

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to Azure VM
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_VM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/id_rsa ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} 
        ls -la
        # cd node-llm 
        # git pull origin master 
        # git diff HEAD..origin/develop
        # npm run build
        # pm2 restart 2
