name: Deploy SSH VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: 13.93.3.248
        username: azureuser
        key: ${{ env.AZURE_VM_KEY }}
        script: |
          cd node-llm
          echo 'Launching git pull...'
          git pull origin develop
          echo 'Showing diff...'
          git diff HEAD^ HEAD
          # npm run build
          # pm2 restart 2
