name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build website image
      run: | 
        docker build --platform linux --tag crissancar/training:latest
    - name: Publish website image
      run: |
        docker push crissancar/training:latest
  deploy:
    name: Web App deploy
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - name: App service auth
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'crissancarapi'
        publish-profile: ${{ secrets.AZURE_APPSERVICE_PUBLISH_PROFILE }}
        images: 'crissancar/training:latest'