name: Deploy

on:
  push:
    branches: [master]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} 
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }} 

jobs:
  push_to_registry:
    name: Push image to registry
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_REPOSITORY }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
          
  deploy:
    name: Deploy image to Azure
    needs: push_to_registry
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - name: App Service deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'crissancarapi'
        publish-profile: ${{ secrets.AZURE_APPSERVICE_PUBLISH_PROFILE }}
        images: ${{ env.DOCKERHUB_REPOSITORY }}:latest
