name: Deploy

on:
  push:
    branches: [master]
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} 
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }} 
  AZURE_REGISTRY_SERVER: ${{ secrets.AZURE_REGISTRY_SERVER }}
  AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
  AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

jobs:
  push_to_registry:
    name: Push image to Azure Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.AZURE_REGISTRY_SERVER }}
          username: ${{ env.AZURE_REGISTRY_USERNAME }}
          password: ${{ env.AZURE_REGISTRY_PASSWORD }}
          
      - name: Build and push images to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.AZURE_REGISTRY_SERVER }}/api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
          
  deploy:
    name: Deploy image to Azure
    runs-on: ubuntu-latest
    needs: push_to_registry

    steps:
    - name: App Service deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: crissancarapi
        publish-profile: ${{ secrets.AZURE_APPSERVICE_PUBLISH_PROFILE }}
        images: ${{ env.AZURE_REGISTRY_SERVER }}/api:latest
