name: Github Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (major, minor, patch)'
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Debug version type
      run: echo "Version type is '${{ github.event.inputs.version }}'"

    - name: Bump version
      id: package
      uses: phips28/gh-action-bump-version@master
      with:
        tag-prefix: 'v'
        -type: ${{ github.event.inputs.version }}
        commit-message: 'Release {{version}} [skip ci]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug bump version output
      run: echo "${{ toJson(steps.package.outputs) }}"

    - name: Create CHANGELOG.md
      run: |
        echo "# Changelog" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "## [${{ steps.package.outputs.newTag }}] - $(date +'%Y-%m-%d')" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "### Pull Requests" >> CHANGELOG.md
        git log --merges --pretty=format:"- %h %s" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "### Commits" >> CHANGELOG.md
        git log --no-merges --pretty=format:"- %h %s" >> CHANGELOG.md

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.package.outputs.newTag }}
        release_name: ${{ steps.package.outputs.newTag }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
