name: Build and deploy Node.js app to Dockerhub

on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }} 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Check repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ../../
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPOSITORY }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
          