name: v4

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (major, minor, patch)'
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Debug version type
      run: echo "Version type is '${{ github.event.inputs.version }}'"

    - name: Bump version
      id: package
      uses: phips28/gh-action-bump-version@master
      with:
        tag-prefix: 'v'
        -type: ${{ github.event.inputs.version }}
        commit-message: 'ci: bumps version to {{version}} [skip ci]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug bump version output
      run: echo "${{ toJson(steps.package.outputs) }}"

    - name: Generate changelog
      uses: mikepenz/release-changelog-builder-action@v2
      with:
        commitMode: true
        configurationJson: |
          {
            "output": "CHANGELOG.md",
            "future-release": "${{ steps.package.outputs.newTag }}"
            "template": "#{{CHANGELOG}}",
            "categories": [
              {
                  "title": "## Feature",
                  "labels": ["feat", "feature"]
              },
              {
                  "title": "## Fix",
                  "labels": ["fix", "bug"]
              },
              {
                  "title": "## Other",
                  "labels": []
              }
            ],
            "label_extractor": [
              {
                "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                "target": "$1"
              }
            ],
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create empty CHANGELOG.md if not exist
      run: touch CHANGELOG.md

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.package.outputs.newTag }}
        release_name: ${{ steps.package.outputs.newTag }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false

