name: Release v2

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type to release (major, minor, patch)'
        required: true

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} 
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }} 
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Get owner info
      id: get_info
      run: |
        OWNER_NAME=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }} | jq .owner.login -r)
        OWNER_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/$OWNER_NAME | jq .email -r)
        echo "::set-output name=owner_name::$OWNER_NAME"
        echo "::set-output name=owner_email::$OWNER_EMAIL"

    - name: Set git user
      run: |
        git config --global user.email "${{ steps.get_info.outputs.owner_email }}"
        git config --global user.name "${{ steps.get_info.outputs.owner_name }}"
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # - name: Calculate next version
    #   id: next_version
    #   uses: slime-hatena/semantic-versioning-calculator-action@main
    #   with:
    #     version: ${{ github.event.inputs.version }}
    - name: Bump version in package.json
      run: |
        npm version ${{ github.event.inputs.version }}
        git push --tags
        
    - name: Generating changelog
      id: changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.4
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Create GitHub release
      id: create_release
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{ steps.next_version.outputs.version }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
        token: ${{ secrets.GH_TOKEN }}
